CREATE TABLE IF NOT EXISTS submission (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    discord_user TEXT NOT NULL,
    date DATE NOT NULL,
    verified BOOLEAN DEFAULT FALSE,
    name TEXT,
    enlist_date TEXT,
    max_kills INTEGER,
    max_friendly_fire INTEGER,
    friends INTEGER,
    enemy_kills INTEGER,
    terminid_kills INTEGER,
    automaton_kills INTEGER,
    illuminate_kills INTEGER,
    friendly_kills INTEGER,
    grenade_kills INTEGER,
    melee_kills INTEGER,
    deaths INTEGER,
    player_level INTEGER,
    missions_played INTEGER,
    missions_won INTEGER,
    mission_time INTEGER,
    samples_collected INTEGER,
    experience INTEGER
);
